### ISSUE TITLE
Please fixed the website title

### ISSUE THREAD

**Issue by shijiezhou1** [chaosforfun/chaosforfun.github.io#1]
Please fixed the website title

**Comment by chaosforfun** [comment]
Im sorry, but what's wrong with the title?

**Comment by shijiezhou1** [comment]
I wish you can accept that change that I made. Thank you.

That can be the right markdown format.

**Comment by chaosforfun** [comment]
where your change? i don't see any pull requests.

**Comment by shijiezhou1** [comment]
Really let me change it again

**Comment by chaosforfun** [comment]
how you changed it? i can't see any thing?
